require(mgcv)
library(mgcv.maps)
#set.seed(100)
dat <- gamSim(1,n=1000,scale=1,dist = "binary")

b<-bam(y~s(x0,bs="Amatern",k=10,m=300,xt=list(getA=piecewise_linearity,para=0.5))+s(x1,bs="Amatern",k=10,m=300,xt=list(getA=piecewise_linearity,para=0.4))
     +s(x2,bs="Amatern",k=10,m=300,xt=list(getA=piecewise_linearity,para=c(0.24,0.5,0.7)))+s(x3,bs="Amatern",m=300,k=10),data=dat,method="REML",family="binomial",select=F)
fitb=summary(b)
plot(b,pages=1)
summary(b)
mgcv_maps_wald(b)

b1<-bam(y~s(x0,bs="ad")+s(x1,bs="ad")
     +s(x2,bs="ad")+s(x3,bs="ad"),data=dat,method="REML",family="binomial",select=F)
plot(b1,pages=1)
summary(b1)
mgcv_maps_wald(b1)
