#' @importFrom CppMatrix matrixMultiply
#' @importFrom Matrix bdiag
#' @export
smooth.construct.mix_cosine.smooth.spec <- function(object, data, knots) {
  delta <- object$p.order[1]
  x <- data[[object$term]]
  n <- length(x)

  # Obtain or define default getA
  if (is.null(object$xt$getA)) {
    getA <- function(x,para) as.matrix(x)  # Default to using x itself
    para = 0
    A <- getA(x)
  } else {
    getA <- object$xt$getA
    para =  object$xt$para
    A <- getA(x,para)
  }

  # Check dimensions
  if (!is.matrix(A)) {
    stop("'getA(x)' must return a matrix.")
  }
  if (nrow(A) != n) {
    stop("The number of rows in matrix 'A' returned by getA(x) must match length of x.")
  }

  object$getA <- getA  # store function for later use
  object$para = para
  m <- ncol(A)

  # Set default bs.dim
  if (object$bs.dim < 0) object$bs.dim <- 10
  if (object$bs.dim <= m) stop("The smoothing dimension 'k' is too small given the fixed effects.")

  object$m <- m
  if (is.na(delta)) delta <- 4
  object$delta <- delta

  # Compute matrix B
  funi <- ecdf(x)
  xi <- funi(x)
  B <- outer(xi, 1:(object$bs.dim-m), function(x, k) cos(k * pi * x))
  svec <- (1:(object$bs.dim-m))^delta

  # Combine matrices A and B
  C <- cbind(A, B)

  # QR decomposition
  G <- matrixMultiply(t(C), A)/n
  fitqr <- qr(G)
  Q <- qr.Q(fitqr, complete = TRUE)[, (m + 1):nrow(G), drop = FALSE]
  X <- cbind(A, matrixMultiply(C,Q))
  svec <- c(rep(0, m), svec)
  Omega <- matrixMultiply(t(Q),Q*svec)
  Omega <- Matrix::bdiag(matrix(0, m, m), Omega)
  Omega <- as.matrix(Omega)

  object$X <- X
  if (!object$fixed) {
    object$S[[1]] <- (Omega + t(Omega)) / 2
  }
  object$rank <- object$bs.dim - m
  object$null.space.dim <- m
  object$null.project <- Q
  object$df <- ncol(X)

  class(object) <- c("mix_cosine.smooth", "mgcv.smooth")
  object
}


#' @importFrom CppMatrix matrixMultiply
#' @importFrom Matrix bdiag
#' @export
Predict.matrix.mix_cosine.smooth <- function(object, data) {
  x_new <- data[[object$term]]
  n_new <- length(x_new)

  # Generate A matrix using stored function
  A_new <- object$getA(x_new,object$para)

  # Check dimensions
  if (!is.matrix(A_new)) {
    stop("'getA(x)' must return a matrix during prediction.")
  }
  if (nrow(A_new) != n_new) stop("The number of rows in A generated by getA(x) must match new data length.")

  m <- ncol(A_new)
  Q <- object$null.project

  funi <- ecdf(x_new)
  xi <- funi(x_new)
  B <- outer(xi, 1:(object$bs.dim-m), function(x, k) cos(k * pi * x))

  # Combine A and B for prediction
  C <- cbind(A_new, B)
  X <- cbind(A_new, matrixMultiply(C,Q))

  X
}
