#' @usage \method{Predict.matrix}{A2Matern.smooth}(object, data)
#' @importFrom mgcv smooth.construct Predict.matrix
#' @importFrom CppMatrix matrixMultiply matrixListProduct
#' @importFrom Matrix bdiag
#' @export
Predict.matrix.A2Matern.smooth <- function(object, data) {
x1 <- data[[object$term[1]]]
x2 <- data[[object$term[2]]]
n = length(x1)
# Generate A matrix using stored function
A<- object$getA(x1,x2,object$para)
# Check dimensions
if (!is.matrix(A)) {
  stop("'getA(x)' must return a matrix during prediction.")
}
if (nrow(A) != n) stop("The number of rows in A generated by getA(x) must match new data length.")

m <- ncol(A)
Q <- object$null.project
lambda_matern = object$lambda_matern
kappa_matern = object$kappa_matern
fit_design=matern_basis_2d(x1=x1,x2=x2,kappa1=kappa_matern$kappa1,kappa2=kappa_matern$kappa2,lambda=lambda_matern)
B=fit_design$DX
Omega=fit_design$DK
C <- cbind( A, B)
X=cbind(A,matrixMultiply(C,Q))
X
}
