#' @importFrom CppMatrix matrixMultiply
#' @importFrom Matrix bdiag
#' @importFrom mgcv smooth.construct Predict.matrix
#' @export
Predict.matrix.Acosine.smooth <- function(object, data) {
  x_new <- data[[object$term]]
  n_new <- length(x_new)

  # Generate A matrix using stored function
  A_new <- object$getA(x_new,object$para)

  # Check dimensions
  if (!is.matrix(A_new)) {
    stop("'getA(x)' must return a matrix during prediction.")
  }
  if (nrow(A_new) != n_new) stop("The number of rows in A generated by getA(x) must match new data length.")

  m <- ncol(A_new)
  Q <- object$null.project

  funi <- ecdf(x_new)
  xi <- funi(x_new)
  B <- outer(xi, 1:(object$bs.dim-m+1), function(x, k) cos(k * pi * x))

  # Combine A and B for prediction
  C <- cbind(A_new, B)
  X <- cbind(A_new, matrixMultiply(C,Q))

  X
}
