# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cox_peto_suffstat <- function(X, eta, time, status) {
    .Call(`_mgcv_taps_cox_peto_suffstat`, X, eta, time, status)
}

gammfast_gaussian_cache <- function(A, B, id, n_threads = 1L) {
    .Call(`_mgcv_taps_gammfast_gaussian_cache`, A, B, id, n_threads)
}

gammfast_gaussian_blup_cached <- function(BtB, BtA, G, beta, sigma2) {
    .Call(`_mgcv_taps_gammfast_gaussian_blup_cached`, BtB, BtA, G, beta, sigma2)
}

gammfast_gaussian_projected_cached <- function(AtA, BtB, BtA, G, sigma2, mean_penalty) {
    .Call(`_mgcv_taps_gammfast_gaussian_projected_cached`, AtA, BtB, BtA, G, sigma2, mean_penalty)
}

gammfast_gaussian_crossprod_cached <- function(AtA, BtB, BtA, H, n_threads = 1L) {
    .Call(`_mgcv_taps_gammfast_gaussian_crossprod_cached`, AtA, BtB, BtA, H, n_threads)
}

gammfast_gaussian_crossprod <- function(A, B, id, H, n_threads = 1L) {
    .Call(`_mgcv_taps_gammfast_gaussian_crossprod`, A, B, id, H, n_threads)
}

gammfast_gaussian_moments <- function(residual, B, id, G, sigma2, n_threads = 1L) {
    .Call(`_mgcv_taps_gammfast_gaussian_moments`, residual, B, id, G, sigma2, n_threads)
}

gammfast_vinv_apply <- function(A, B, id, G, R_diag, n_threads = 1L) {
    .Call(`_mgcv_taps_gammfast_vinv_apply`, A, B, id, G, R_diag, n_threads)
}

gammfast_laplace_influence_cached <- function(X, B, id, G, working_BtB, working_BtA, working_mean_covariance, determinant_BtB, determinant_BtA, determinant_mean_covariance, determinant_derivative, u, scale = 1.0, same_curvature = FALSE, n_threads = 1L) {
    .Call(`_mgcv_taps_gammfast_laplace_influence_cached`, X, B, id, G, working_BtB, working_BtA, working_mean_covariance, determinant_BtB, determinant_BtA, determinant_mean_covariance, determinant_derivative, u, scale, same_curvature, n_threads)
}

gammfast_variance_quadratic <- function(response, X, beta, B, id, G, R_diag, penalty, probes, exact, eigen_tol = 1e-8, n_threads = 1L) {
    .Call(`_mgcv_taps_gammfast_variance_quadratic`, response, X, beta, B, id, G, R_diag, penalty, probes, exact, eigen_tol, n_threads)
}

native_re_uid_profile_create_cpp <- function(dense, local, group, weight, dense_penalty, local_penalty, n_threads = 1L) {
    .Call(`_mgcv_taps_native_re_uid_profile_create_cpp`, dense, local, group, weight, dense_penalty, local_penalty, n_threads)
}

native_re_uid_profile_apply_cpp <- function(pointer, value, schur_inverse) {
    .Call(`_mgcv_taps_native_re_uid_profile_apply_cpp`, pointer, value, schur_inverse)
}

ocat_folded <- function(eta, y_int, alpha, eps_mu = 1e-12, eps_w = 1e-12, clip_eta_min = -20.0, clip_eta_max = 20.0, n_threads = 1L) {
    .Call(`_mgcv_taps_ocat_folded`, eta, y_int, alpha, eps_mu, eps_w, clip_eta_min, clip_eta_max, n_threads)
}

