# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cox_cloglog_folded <- function(time, status, strata, eta, bh_time_list, bh_hazard_list, K_per_strata, eps_delta = 1e-12, eps_prob = 1e-12, eps_muprime = 1e-12, clip_eta_min = -20.0, clip_eta_max = 20.0, n_threads = 1L) {
    .Call(`_mgcv_taps_cox_cloglog_folded`, time, status, strata, eta, bh_time_list, bh_hazard_list, K_per_strata, eps_delta, eps_prob, eps_muprime, clip_eta_min, clip_eta_max, n_threads)
}

ocat_folded <- function(eta, y_int, alpha, eps_mu = 1e-12, eps_w = 1e-12, clip_eta_min = -20.0, clip_eta_max = 20.0, n_threads = 1L) {
    .Call(`_mgcv_taps_ocat_folded`, eta, y_int, alpha, eps_mu, eps_w, clip_eta_min, clip_eta_max, n_threads)
}

